/**
 * Mock Data for Development
 * Simulates a database response
 */

export const mockProducts = [
  {
    id: 1,
    promotion: "-75%",
    image:
      "https://wmg.stylekorean.com/BR000189/cosSM13-SC_3_thumb.jpg?v20240210",
    title: "All-Around Safe Block Essence Sun SPF45+",
    product: "All Around Safe Block Sun Milk SPF50+/PA+++",
    rating: 4.5,
    ratingCount: 156,
    price: "$99.00",
    originalPrice: "$396.00",
    category: "Sunscreen",
    brand: "COSRX",
    skinType: ["All Skin", "Sensitive"],
    tags: ["SPF", "Daily Care", "Lightweight"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 2,
    promotion: "-25%",
    image:
      "https://wmg.stylekorean.com/BR000189/cosS21-AL_thumb.jpg?v20240210",
    title: "Hydrating Cleansing Balm",
    product: "Deep Clean Cleansing Balm",
    rating: 4.8,
    ratingCount: 203,
    price: "$32.00",
    originalPrice: "$42.67",
    category: "Cleansing Balm",
    brand: "Banila Co",
    skinType: ["Dry", "Normal"],
    tags: ["Double Cleanse", "Makeup Remover", "Hydrating"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 3,
    promotion: "-25%",
    image:
      "https://wmg.stylekorean.com/BR000208/7KCc66qp7JeG7J2M2_thumb.jpg?v20240210",
    title: "Vitamin C Brightening Serum",
    product: "Pure Vitamin C Serum",
    rating: 4.7,
    ratingCount: 189,
    price: "$32.00",
    originalPrice: "$42.67",
    category: "Serum",
    brand: "Klairs",
    skinType: ["All Skin", "Dull"],
    tags: ["Brightening", "Anti-aging", "Vitamin C"],
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    id: 4,
    promotion: "-10%",
    image:
      "https://wmg.stylekorean.com/BR000456/HRS04-I_1_thumb.jpg?v20240210",
    title: "Hyaluronic Acid Toner",
    product: "Deep Hydration Toner",
    rating: 4.6,
    ratingCount: 142,
    price: "$32.00",
    originalPrice: "$35.56",
    category: "Toner",
    brand: "Hada Labo",
    skinType: ["Dry", "Normal", "Combination"],
    tags: ["Hydrating", "Plumping", "Hyaluronic Acid"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 5,
    promotion: "-50%",
    image: "https://wmg.stylekorean.com/HMC01-NewBalmR_thumb.jpg?v20240210",
    title: "Gentle Cleansing Oil",
    product: "Ultra Light Cleansing Oil",
    rating: 4.9,
    ratingCount: 287,
    price: "$32.00",
    originalPrice: "$64.00",
    category: "Oil Cleanser",
    brand: "DHC",
    skinType: ["All Skin", "Sensitive"],
    tags: ["Double Cleanse", "Gentle", "Makeup Remover"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 6,
    promotion: "-10%",
    image:
      "https://wmg.stylekorean.com/BR000389/7IKs7J207KaI33_thumb.jpg?v20240210",
    title: "Niacinamide Essence",
    product: "Galactomyces Niacin Essence",
    rating: 4.7,
    ratingCount: 178,
    price: "$32.00",
    originalPrice: "$35.56",
    category: "Essence",
    brand: "COSRX",
    skinType: ["All Skin", "Oily"],
    tags: ["Brightening", "Pore Care", "Niacinamide"],
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    id: 7,
    promotion: "-75%",
    image:
      "https://wmg.stylekorean.com/BR000537/AXS04-SD_thumb_1.jpg?v20240210",
    title: "Snail Mucin Cream",
    product: "Advanced Snail 92 All In One Cream",
    rating: 4.8,
    ratingCount: 312,
    price: "$32.00",
    originalPrice: "$128.00",
    category: "Moisturizer",
    brand: "COSRX",
    skinType: ["All Skin", "Dry"],
    tags: ["Hydrating", "Repairing", "Snail Mucin"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 8,
    promotion: "-25%",
    image: "https://wmg.stylekorean.com/JSMP05-PK_thumb.jpg?v20240210",
    title: "AHA/BHA Exfoliating Toner",
    product: "Chemical Exfoliating Toner",
    rating: 4.5,
    ratingCount: 165,
    price: "$32.00",
    originalPrice: "$42.67",
    category: "Exfoliator",
    brand: "Some By Mi",
    skinType: ["Oily", "Combination", "Acne-Prone"],
    tags: ["Exfoliating", "Pore Care", "AHA", "BHA"],
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    id: 9,
    promotion: "",
    image:
      "https://wmg.stylekorean.com/BR000296/HLSS01-SR_thumb_1.jpg?v20240210",
    title: "Green Tea Cleansing Foam",
    product: "Refreshing Foam Cleanser",
    rating: 4.4,
    ratingCount: 98,
    price: "$32.00",
    originalPrice: "$32.00",
    category: "Foam Cleanser",
    brand: "Innisfree",
    skinType: ["Normal", "Combination", "Oily"],
    tags: ["Cleansing", "Green Tea", "Fresh"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 10,
    promotion: "-25%",
    image: "https://wmg.stylekorean.com/RNCM17-LM06_thumb.jpg?v20240210",
    title: "Retinol Eye Cream",
    product: "Advanced Retinol Eye Serum",
    rating: 4.6,
    ratingCount: 134,
    price: "$32.00",
    originalPrice: "$42.67",
    category: "Eye Care",
    brand: "The Ordinary",
    skinType: ["All Skin"],
    tags: ["Anti-aging", "Retinol", "Eye Care"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 11,
    promotion: "-10%",
    image:
      "https://wmg.stylekorean.com/BR000389/JSMS01-4SET_thumb.jpg?v20240210",
    title: "Sheet Mask Set",
    product: "Essential Mask Sheet Collection",
    rating: 4.7,
    ratingCount: 221,
    price: "$32.00",
    originalPrice: "$35.56",
    category: "Face Mask",
    brand: "Mediheal",
    skinType: ["All Skin"],
    tags: ["Hydrating", "Variety Pack", "Soothing"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 12,
    promotion: "-75%",
    image:
      "https://sokoskins.shop/cdn/shop/files/51L5-xrUBLL._SL1500_1500x.jpg?v=1694879625",
    title: "Cica Repair Cream",
    product: "Centella Asiatica Recovery Cream",
    rating: 4.9,
    ratingCount: 345,
    price: "$32.00",
    originalPrice: "$128.00",
    category: "Moisturizer",
    brand: "Dr. Jart+",
    skinType: ["Sensitive", "Irritated", "All Skin"],
    tags: ["Soothing", "Repairing", "Centella"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 13,
    promotion: "-30%",
    image: "https://ohlolly.com/cdn/shop/products/Ohlolly-Cosrx-Propolis-Light-Ampoule-2.jpg?v=1758154298&width=975",
    title: "Propolis Light Ampoule",
    product: "Honey Glow Propolis Serum",
    rating: 4.8,
    ratingCount: 267,
    price: "$28.00",
    originalPrice: "$40.00",
    category: "Serum",
    brand: "COSRX",
    skinType: ["All Skin", "Dry", "Dull"],
    tags: ["Brightening", "Honey", "Propolis", "Glow"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 14,
    promotion: "",
    image: "https://d1iuscsovtvj4y.cloudfront.net/products/8809153100641_1.jpg",
    title: "Rice Mask Wash Off",
    product: "Brightening Rice Overnight Mask",
    rating: 4.5,
    ratingCount: 187,
    price: "$24.00",
    originalPrice: "$24.00",
    category: "Face Mask",
    brand: "Innisfree",
    skinType: ["Normal", "Dry"],
    tags: ["Brightening", "Rice Extract", "Overnight Mask"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 15,
    promotion: "-20%",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgxF3qk3CF6bdSoGAp0N-JtZotSnhjqoZxLQ&s",
    title: "Peptide Firming Serum",
    product: "Multi Peptide Anti-Aging Serum",
    rating: 4.7,
    ratingCount: 198,
    price: "$36.00",
    originalPrice: "$45.00",
    category: "Serum",
    brand: "The Ordinary",
    skinType: ["All Skin", "Mature"],
    tags: ["Anti-aging", "Peptide", "Firming"],
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    id: 16,
    promotion: "-40%",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYfB-lHXHMk9OV6x5FGhqh95MWSEOJfMv68g&s",
    title: "Tea Tree Spot Treatment",
    product: "Acne Clear Tea Tree Essence",
    rating: 4.6,
    ratingCount: 223,
    price: "$18.00",
    originalPrice: "$30.00",
    category: "Treatment",
    brand: "Some By Mi",
    skinType: ["Oily", "Acne-Prone", "Combination"],
    tags: ["Acne", "Tea Tree", "Spot Treatment"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 17,
    promotion: "",
    image: "https://www.drjart.com/media/export/cms/products/1000x1000/dj_sku_H7T901_1000x1000_0.jpg",
    title: "Ceramide Moisture Cream",
    product: "Barrier Repair Ceramide Cream",
    rating: 4.8,
    ratingCount: 301,
    price: "$38.00",
    originalPrice: "$38.00",
    category: "Moisturizer",
    brand: "Dr. Jart+",
    skinType: ["Dry", "Sensitive", "All Skin"],
    tags: ["Ceramide", "Barrier Repair", "Hydrating"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 18,
    promotion: "-15%",
    image: "https://us.innisfree.com/cdn/shop/files/1IF_V-CM_PDP_01_Packshot_2024_1080x1080_cbbd6762-1ece-4aaa-a06b-0fb4290b37c8_1.jpg?v=1759868439",
    title: "Charcoal Clay Mask",
    product: "Deep Pore Cleansing Clay Mask",
    rating: 4.4,
    ratingCount: 156,
    price: "$22.00",
    originalPrice: "$26.00",
    category: "Face Mask",
    brand: "Innisfree",
    skinType: ["Oily", "Combination"],
    tags: ["Pore Care", "Charcoal", "Deep Cleansing"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 19,
    promotion: "-50%",
    image: "https://main.thgimages.com/?url=https://static.thcdn.com/productimg/original/16858548-1935256688673721.jpg&format=webp&width=1500&height=1500&fit=cover",
    title: "Collagen Boosting Toner",
    product: "Hydrating Collagen Toner Pad",
    rating: 4.7,
    ratingCount: 189,
    price: "$25.00",
    originalPrice: "$50.00",
    category: "Toner",
    brand: "Mediheal",
    skinType: ["All Skin", "Mature"],
    tags: ["Collagen", "Anti-aging", "Toner Pad"],
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    id: 20,
    promotion: "",
    image: "https://sokoskins.shop/cdn/shop/products/public_1152_525x.jpg?v=1734944662",
    title: "Salicylic Acid Cleanser",
    product: "BHA Blackhead Power Liquid",
    rating: 4.6,
    ratingCount: 278,
    price: "$26.00",
    originalPrice: "$26.00",
    category: "Exfoliator",
    brand: "COSRX",
    skinType: ["Oily", "Acne-Prone"],
    tags: ["BHA", "Blackhead", "Pore Care"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 21,
    promotion: "-35%",
    image: "https://kosallure.com/cdn/shop/files/GinsengEssenceWater_pkg.jpg?v=1713992422&width=1445",
    title: "Ginseng Essence Water",
    product: "Revitalizing Ginseng Essence",
    rating: 4.9,
    ratingCount: 412,
    price: "$39.00",
    originalPrice: "$60.00",
    category: "Essence",
    brand: "Sulwhasoo",
    skinType: ["All Skin", "Mature", "Dry"],
    tags: ["Ginseng", "Anti-aging", "Revitalizing"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 22,
    promotion: "-20%",
    image: "https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//d/e/dear-klairs-freshly-juiced-vitamin-e-mask-90g.jpg",
    title: "Vitamin E Moisturizer",
    product: "Nourishing Vitamin E Cream",
    rating: 4.5,
    ratingCount: 145,
    price: "$28.00",
    originalPrice: "$35.00",
    category: "Moisturizer",
    brand: "Klairs",
    skinType: ["Dry", "Normal"],
    tags: ["Vitamin E", "Nourishing", "Hydrating"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 23,
    promotion: "-60%",
    image: "https://static.beautytocare.com/cdn-cgi/image/f=auto/media/catalog/product//c/o/cosrx-advanced-snail-96-mucin-power-essence-100ml.jpg",
    title: "Snail Mucin Essence",
    product: "Advanced Snail 96 Mucin Power Essence",
    rating: 4.9,
    ratingCount: 523,
    price: "$20.00",
    originalPrice: "$50.00",
    category: "Essence",
    brand: "COSRX",
    skinType: ["All Skin", "Dry"],
    tags: ["Snail Mucin", "Hydrating", "Repairing"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 24,
    promotion: "",
    image: "https://i5.walmartimages.com/seo/Aloe-Vera-Soothing-Gel-100-Pure-Moisturizer-300-ml_8be9c4ee-ee3f-401b-b961-34cb67676717_1.145d8e71f2b695bca1b062efc8466dce.png",
    title: "Aloe Vera Soothing Gel",
    product: "Fresh Aloe 99% Soothing Gel",
    rating: 4.3,
    ratingCount: 234,
    price: "$12.00",
    originalPrice: "$12.00",
    category: "Moisturizer",
    brand: "Nature Republic",
    skinType: ["All Skin", "Sensitive"],
    tags: ["Aloe Vera", "Soothing", "Cooling"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 25,
    promotion: "-25%",
    image: "https://sokoskins.shop/cdn/shop/files/birch-moisturizing-cream-round-lab-1_1024x1024@2x.webp?v=1699541490",
    title: "Birch Juice Moisturizer",
    product: "Hydrating Birch Sap Lotion",
    rating: 4.6,
    ratingCount: 167,
    price: "$30.00",
    originalPrice: "$40.00",
    category: "Moisturizer",
    brand: "Round Lab",
    skinType: ["All Skin", "Sensitive"],
    tags: ["Birch Sap", "Hydrating", "Gentle"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 26,
    promotion: "-45%",
    image: "https://sokoskins.shop/cdn/shop/files/anua-us-toner-heartleaf-77-soothing-toner-1161173062_2000x.webp?v=1759579193",
    title: "Heartleaf Toner",
    product: "Calming Heartleaf 77% Toner",
    rating: 4.8,
    ratingCount: 389,
    price: "$22.00",
    originalPrice: "$40.00",
    category: "Toner",
    brand: "Anua",
    skinType: ["Sensitive", "Acne-Prone", "All Skin"],
    tags: ["Heartleaf", "Calming", "Soothing"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 27,
    promotion: "",
    image: "https://d2c3d01lcpw2ui.cloudfront.net/gl/data/item/1713406164/InnisfreeS.VolcanicP.ClayMask100ml.jpg",
    title: "Volcanic Pore Clay Mask",
    product: "Jeju Volcanic Clay Mask",
    rating: 4.5,
    ratingCount: 201,
    price: "$20.00",
    originalPrice: "$20.00",
    category: "Face Mask",
    brand: "Innisfree",
    skinType: ["Oily", "Combination"],
    tags: ["Volcanic Clay", "Pore Care", "Sebum Control"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 28,
    promotion: "-30%",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrqfz3Hf5tryGOFVwuLecxE5LUlbLX-c3w_A&s",
    title: "Matcha Green Tea Serum",
    product: "Antioxidant Matcha Serum",
    rating: 4.6,
    ratingCount: 178,
    price: "$28.00",
    originalPrice: "$40.00",
    category: "Serum",
    brand: "Innisfree",
    skinType: ["All Skin", "Oily"],
    tags: ["Matcha", "Antioxidant", "Green Tea"],
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    id: 29,
    promotion: "-70%",
    image: "https://glammerstudio.com/cdn/shop/files/2023-08-16-ORD-Visual-Lifestyle-HA-2pct-B5-HMH-04-1x1_1445x_9a9b0757-3f37-4398-adda-d99d46ee2e5e.webp?v=1745437866",
    title: "Hyaluronic Acid Serum",
    product: "Deep Hydration HA Serum",
    rating: 4.7,
    ratingCount: 356,
    price: "$15.00",
    originalPrice: "$50.00",
    category: "Serum",
    brand: "The Ordinary",
    skinType: ["All Skin", "Dry"],
    tags: ["Hyaluronic Acid", "Hydrating", "Plumping"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 30,
    promotion: "",
    image: "https://d2c3d01lcpw2ui.cloudfront.net/gl/data/item/1681714341/67iU656Z7IqI6rGw.jpg",
    title: "Black Sugar Scrub Mask",
    product: "Exfoliating Black Sugar Wash Off Mask",
    rating: 4.4,
    ratingCount: 167,
    price: "$19.00",
    originalPrice: "$19.00",
    category: "Exfoliator",
    brand: "Skinfood",
    skinType: ["All Skin", "Dull"],
    tags: ["Exfoliating", "Brightening", "Sugar Scrub"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 31,
    promotion: "-40%",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEgTDHZQE4HAr3dXmpi9wNYI6ZOUC52eyqjw&s",
    title: "Bakuchiol Retinol Alternative",
    product: "Plant-based Bakuchiol Serum",
    rating: 4.8,
    ratingCount: 289,
    price: "$30.00",
    originalPrice: "$50.00",
    category: "Serum",
    brand: "Beauty of Joseon",
    skinType: ["All Skin", "Sensitive"],
    tags: ["Bakuchiol", "Anti-aging", "Gentle"],
    inStock: true,
    featured: true,
    bestSeller: false,
  },
  {
    id: 32,
    promotion: "-15%",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHJ8pqI02KRkKCv_QjhKgUoIpibDgCO7Xthg&s",
    title: "Milk Peeling Toner",
    product: "AHA/PHA Gentle Peeling Toner",
    rating: 4.5,
    ratingCount: 192,
    price: "$25.50",
    originalPrice: "$30.00",
    category: "Toner",
    brand: "Some By Mi",
    skinType: ["All Skin", "Sensitive"],
    tags: ["AHA", "PHA", "Gentle Peeling"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 33,
    promotion: "-55%",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdG84xirkysBzSh_S8bdbDz8UTYtO0eQnf8g&s",
    title: "Honey Glow Sleeping Mask",
    product: "Overnight Honey Radiance Mask",
    rating: 4.7,
    ratingCount: 267,
    price: "$18.00",
    originalPrice: "$40.00",
    category: "Face Mask",
    brand: "COSRX",
    skinType: ["All Skin", "Dry", "Dull"],
    tags: ["Sleeping Mask", "Honey", "Brightening"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 34,
    promotion: "",
    image: "https://sokoskins.shop/cdn/shop/products/2-Step-Mugwort-Calming-Set-1_600x.jpg?v=1657338407",
    title: "Mugwort Calming Essence",
    product: "Artemisia Soothing Essence",
    rating: 4.9,
    ratingCount: 401,
    price: "$35.00",
    originalPrice: "$35.00",
    category: "Essence",
    brand: "I'm From",
    skinType: ["Sensitive", "Irritated", "All Skin"],
    tags: ["Mugwort", "Calming", "Anti-inflammatory"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 35,
    promotion: "-20%",
    image: "https://peachesandcremeshop.com/cdn/shop/files/KLAIRS-07-01_ba3ba262-c118-43bb-82cf-8dce9e9f58de.jpg?v=1701257751",
    title: "Peptide Eye Cream",
    product: "Firming Peptide Eye Treatment",
    rating: 4.6,
    ratingCount: 178,
    price: "$32.00",
    originalPrice: "$40.00",
    category: "Eye Care",
    brand: "Klairs",
    skinType: ["All Skin", "Mature"],
    tags: ["Peptide", "Eye Care", "Anti-aging"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 36,
    promotion: "-65%",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcHRkTFEoxnDrgUkNKRn1y_tQLa2QUFB7_Pw&s",
    title: "Niacinamide Brightening Cream",
    product: "10% Niacinamide Glow Cream",
    rating: 4.8,
    ratingCount: 334,
    price: "$21.00",
    originalPrice: "$60.00",
    category: "Moisturizer",
    brand: "Some By Mi",
    skinType: ["All Skin", "Dull", "Oily"],
    tags: ["Niacinamide", "Brightening", "Glow"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 37,
    promotion: "",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ481mmpYsGMSVJkV5xQ4BLSB_JLlsEjB250Q&s",
    title: "Fermented Rice Toner",
    product: "Sake Fermented First Essence",
    rating: 4.7,
    ratingCount: 245,
    price: "$42.00",
    originalPrice: "$42.00",
    category: "Toner",
    brand: "SK-II",
    skinType: ["All Skin", "Dull"],
    tags: ["Fermented", "Brightening", "Rice"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 38,
    promotion: "-30%",
    image: "https://cosmura.es/cdn/shop/files/Purito_Cream-04.png?v=1751900397&width=1200",
    title: "Madecassoside Cream",
    product: "Centella Recovery Gel Cream",
    rating: 4.6,
    ratingCount: 213,
    price: "$24.50",
    originalPrice: "$35.00",
    category: "Moisturizer",
    brand: "Purito",
    skinType: ["Sensitive", "Acne-Prone", "All Skin"],
    tags: ["Centella", "Madecassoside", "Soothing"],
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    id: 39,
    promotion: "-80%",
    image: "https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//e/s/estee-lauder-advanced-night-repair-synchronized-multi-recovery-complex-serum-50ml_1.jpg",
    title: "Advanced Night Repair Serum",
    product: "Intensive Recovery Night Serum",
    rating: 4.9,
    ratingCount: 478,
    price: "$25.00",
    originalPrice: "$125.00",
    category: "Serum",
    brand: "COSRX",
    skinType: ["All Skin", "Mature", "Dry"],
    tags: ["Night Care", "Anti-aging", "Repairing"],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
];
